//import "./lessons/02-first-lesson/main"
//import "./lessons/03-events-and-refs/main"
//import "./lessons/04-events-in-depth/main"
//import "./lessons/05-injecting-a-service/main"
//import "./lessons/06-using-the-inject-decorator/main"
//import "./lessons/07-ng-for/main"
//import "./lessons/08-ng-model/main"
import "./lessons/09-adding-a-model/main"